title: "QuackMage"
description: "Indie Game Developer • Anatine Conjuror"
theme: jekyll-theme-cayman

# Optional navbar links (Cayman will show these if you add header links)
header_pages:
  - index.md
  - projects.md

# GitHub Pages options
show_downloads: false
github:
  is_project_page: false

# Include custom stylesheet
include:
  - assets/custom.css

# Markdown settings
markdown: kramdown
highlighter: rouge
